name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28.2

      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
        with:
          velociraptor-version: 1.5.0

      - name: CI
        run: vr test
